version: "3.9"
services:
  python-app:
    build: .
    container_name: python-app
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    working_dir: /app  # Ensure the working directory is /app
    environment:
      - PYTHONUNBUFFERED=1
    command: bash  # This will start the bash shell for interactive use
