# This is a basic workflow to help you get started with Actions

name: Sample CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from actions tab
  workflow_dispatch:
  
# The jobs that run as part of this workflow
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          make install

      # Lint
      - name: Lint with pylint
        run: |
          make lint
        
      # Run tests
      - name: Run tests with pytest
        run: |
          make test

      # Format code
      - name: Format Code
        run: |
          make format

      # Example step: Echo a message
      - name: Echo message
        run: echo "CI process completed successfully!"
